### ISSUE TITLE
[gatsby-plugin-goatcounter] How to use section in npm page uses ";" instead of commas inside options object

### ISSUE THREAD

**Issue by TedisAgolli** [GaiAma/Coding4GaiAma#29]
https://www.npmjs.com/package/gatsby-plugin-goatcounter

![goatcounter](https://user-images.githubusercontent.com/10348514/89724110-05613080-d9cd-11ea-8ccc-ac526bc7d7b8.png)
age/gatsby-plugin-goatcounter

**Comment by CanRau** [comment]
Ooh good catch thank you I thought I've fixed it 🤔 I've probably missed to upload the updated version to NPM 🤦🏻‍♂️

**Comment by TedisAgolli** [comment]
👍 Thanks for the cool plugin!

**Comment by TedisAgolli** [comment]
Fixed
